import httpx
import os

# Use the audio file generated by the previous test as input
# It contains the spoken text "Hello world"
input_file = "test_fish_audio.wav"

if not os.path.exists(input_file):
    print(f"Error: {input_file} not found. Run test_fish_api.py first.")
    exit(1)

url = "http://localhost:8000/api/fish"
print(f"Sending {input_file} to {url}...")

with open(input_file, "rb") as f:
    files = {"file": ("test.wav", f, "audio/wav")}
    try:
        r = httpx.post(url, files=files, timeout=60.0)
        print(f"Status Code: {r.status_code}")
        if r.status_code == 200:
            print(f"Success! Received {len(r.content)} bytes of audio.")
            with open("test_full_output.wav", "wb") as out:
                out.write(r.content)
            print("Saved result to test_full_output.wav")
        else:
            print(f"Error Response: {r.text}")
    except Exception as e:
        print(f"Request Failed: {e}")
